# app_next/docker-compose.yml
services:
  vault:
    build: ./security/vault
    container_name: vault
    cap_add:
      - IPC_LOCK
    networks:
      - transcendence_net
    volumes:
      - vault_secrets:/vault/config
      - vault_data:/vault/data
      - ssl_certs:/vault/certs

  nginx:
    build: ./security/nginx
    container_name: nginx
    ports:
      - "8443:443"
    depends_on:
      - vault
      - app
    networks:
      - transcendence_net
    volumes:
      - vault_secrets:/vault/config
      - ./security/nginx/conf:/etc/nginx/conf.d
      - ssl_certs:/etc/nginx/ssl:ro
  
  postgres:
    build: ./security/postgres
    container_name: postgres
    networks:
      - transcendence_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - vault_secrets:/vault/config:ro
    depends_on:
      - vault

  app:
    build:
      context: ./app_next
      dockerfile: Dockerfile.dev
    networks:
      - transcendence_net
    volumes:
      - ./app_next:/app
      - /app/node_modules
      - ssl_certs:/vault/certs
      - vault_secrets:/vault/config:ro
      - ssl_certs:/app/certificates:ro
    depends_on:
      - postgres
      - vault

networks:
  transcendence_net:
    driver: bridge

volumes:
  vault_secrets:
  vault_data:
  postgres_data:
  ssl_certs:
