FROM node:20-bullseye-slim

RUN apt-get update && apt-get install -y \
    openssl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json ./


RUN npm ci

COPY ./app-entrypoint.sh /usr/local/bin/app-entrypoint.sh

RUN chmod +x /usr/local/bin/app-entrypoint.sh

COPY prisma ./prisma/

COPY . .

RUN mkdir -p .next && chmod -R 777 .next

EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/app-entrypoint.sh"]