# allume le moteur et définit où écrire les logs
Include /etc/nginx/modsec/modsec.conf

# définit les réglages des règles
Include /etc/modsecurity/crs/crs-setup.conf

# charge les "fiches de recherche" (SQLi, XSS, etc.)
Include /usr/share/modsecurity-crs/rules/*.conf